### ISSUE TITLE
Installation via Eclipse Marketplace fails with 'Unsupported signature algorithm (rsa_pss_rsae_sha256)'

### ISSUE THREAD

**Issue by bergerst** [thymeleaf/thymeleaf-extras-eclipse-plugin#101]
I'm running Eclipse 2020-09 and when I try to install the plugin via Marketplace, the installation fails with `Unsupported signature algorithm (rsa_pss_rsae_sha256)` when downloading from https://dl.bintray.com/thymeleaf/downloads.

Seems like bintray is using a RSASSA PSS cipher, which is not supported by the default JDK. I'm using AdoptOpenJDK version 11.0.9.1.

I can't provide the exact error message since I already installed the plugin manually via the zip, sorry for that.

**Comment by ultraq** [comment]
Gonna close this one now as we've just moved from hosting the plugin artifacts on Bintray to GitHub as Bintray is being shut down (#102).  Did a quick check and it seemed to work OK (then again, so did Bintray at the time), so hopefully the supported algorithms that GitHub use work better with JDK 11.
