### ISSUE TITLE
No repo found plz help 

### ISSUE THREAD

**Issue by Sourabhvarma** [thymeleaf/thymeleaf-extras-eclipse-plugin#103]
No repository found at https://dl.bintray.com/thymeleaf/downloads/thymeleaf-extras-eclipse-plugin/3.0.0/update-site/.
![Capture](https://user-images.githubusercontent.com/61043049/116146027-a75faf00-a6fb-11eb-8eab-03ee9c18a949.PNG)

**Comment by ultraq** [comment]
Hi there, you might have to try again.  Bintray is currently performing service brown-outs during this period, and we're still using bintray to resolve the Eclipse plugin artifacts:

> April 12th, 26th, 2021 | We will have some short service  brown-outs to remind users about the services that are going away on May  1st. (Specific hours will be advertised in the Bintray status page.)
> -- | --

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

We've got an open issue to move these artifacts out of Bintray: #102

**Comment by ultraq** [comment]
Artifacts have now been moved out of Bintray
