### ISSUE TITLE
I am getting "Unable to read repository at http://www.thymeleaf.org/eclipse-plugin-update-site/content.xml." issues while installing in STS 4.6.1

### ISSUE THREAD

**Issue by ManishKumar9570** [thymeleaf/thymeleaf-extras-eclipse-plugin#104]
Please solve this issue or let me know if any solution is there.
![Thymeleaf installation error in STS 4 6 1](https://user-images.githubusercontent.com/58567108/117657266-fce59280-b1b6-11eb-8c89-36ef29b43ac1.png)

**Comment by ultraq** [comment]
I went and downloaded STS 4.6.1 (https://github.com/spring-projects/sts4/wiki/Previous-Versions#spring-tools-461-changelog), and went to install the Thymeleaf Eclipse plugin through the update site URL (http://www.thymeleaf.org/eclipse-plugin-update-site/), and it worked for me.  I tried Java 8 and 11 (from the Adopt OpenJDK project), and I'm using a Mac, so there might be a few differences from here and what you have (looks like Windows).

Was your STS setup created in a similar way, or did you use an Eclipse installation and then added STS atop it, or do you have a different version of Java?  That error about a `content.xml` file looks a bit odd - there is no `content.xml` file with the plugin artifacts, and the error message talking about security validation makes me wonder if maybe whatever version of Java you're using can't do the version of HTTPS that GitHub is serving up?  (GitHub redirects http traffic to https, and we're using GitHub to serve the plugin artifacts.)

**Comment by ultraq** [comment]
If after all of that, you can't get the plugin to install over the internet, you can download a zip file containing the plugin from the releases section and install it from the zip file.  Here's the latest release: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/releases/tag/3.0.0

And in case you need some instructions on how to install from a zip (it's been so long that I forgot how as well! 😅): https://stackoverflow.com/a/16074606

**Comment by ManishKumar9570** [comment]
@ultraq  Firstly thank you for your response. I have tried with java 1.8 in STS but getting error like above one but I have installed with different way and now its working fine.

**Comment by NANDINIJYOTI** [comment]
> @ultraq Firstly thank you for your response. I have tried with java 1.8 in STS but getting error like above one but I have installed with different way and now its working fine.

how did you find the solution ...I am facing similar issue..please share the solution.

**Comment by ManishKumar9570** [comment]
@NANDINIJYOTI It has long year back so I don't remember the solution properly but yeah try to install that software or related software from the eclipse marketplace and check and also let me know whether you face the same issue or not.

**Comment by NANDINIJYOTI** [comment]
Hey Manish ,
Thankyou soo much for your response I wasn't expecting any reply though.
Good thing is I resolved the issue .What I did is I installed thymeleaf and
then imported to STS and eclipse.Its working fine now.
Thanks again:)

**Comment by ManishKumar9570** [comment]
@NANDINIJYOTI Hey Nandini, Sorry for the late response but I don't open my mail frequently and thank you for response that you have got the solution and also provided the same for another folks for future reference. 
Thanks

**Comment by jagdish590** [comment]
Hi @NANDINIJYOTI  could you please let me know the solution How you resolved it.  I am also getting same issue. I have tried eclipse market place and install new software options
