### ISSUE TITLE
Plugin not available in Sourceforge

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf-extras-eclipse-plugin#14]
Maybe it's a french-localized issue but I can't access the SourceForge site for 2 days. Could it be possible to upload the latest release of the plugin in GitHub? Or in another place?

Thanks
Thibault.

**Comment by danielfernandez** [comment]
Strange... this link http://sourceforge.net/projects/thymeleaf/files/thymeleaf-extras-eclipse-plugin/2.0.1/ works perfectly OK from here...

The reason we are using SourceForge for distributing these packages is GitHub recently removed the "Downloads" section from their project hosting facilities, so there is no way --no way allowed by the Terms of Use-- to distribute a binary package from GitHub right now :-(
