### ISSUE TITLE
Improve the "restriction" feature

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf-extras-eclipse-plugin#17]
Hi again :-)

Still regarding Dandelion-Datatables, the needed restrictions are mostly a bit more complex than just restricting to a HTML tag.
Actually, I would like to be able to restrict the proposed processors depending on the presence of other processors.

For instance, in the following code snippet :

```
<table id="myTableId" dt:table="true" dt:url="/persons" dt:serverside="true" dt:serverparams="getCustomParams" >
```

The `dt:serverparams` attribute can be added only if the `dt:serverside` attribute is already present in the HTML table tag.

Is that feasible?

**Comment by ultraq** [comment]
That should be doable :)  I'm thinking it can be another attribute to the `<restrictions>` tag that lists other processors that must be present within the same element before it can be suggested.

Just thinking about the 'user experience' of such a feature (or developer experience in our case), this might impose an order on which a developer can add the `dt:` processors to the `table` element.  Say they discover in your dialect docs that `dt:serverparams` is something they want to use, but when they start typing it and the suggestion doesn't show up.  The answer is to consult your docs again and realize that it needs `dt:serverside="true"` first, but the lack of suggestion might be confusing.

Of course, this might be _exactly_ what you want to happen, and you're just using the restrictions to create some 'good programmer habits' when using your dialect.

This actually raises 2 other things I want to do:
- adding restrictions to the documentation that appears with the content assist (#18)
- maybe raising validation warnings if the restrictions are not followed (#19)

**Comment by ultraq** [comment]
Added a new attribute, `attributes`, which acts just like `tags`, except this time it's a list of attributes that must or must not appear in the same tag as the processor suggestion.

For your example, you should be able to make `dt:serverparams` only appear in the content assist if `dt:serverside` is present, by adding the following to the `dt:serverparams` definition:

``` xml
<restrictions attributes="dt:serverside"/>
```
