### ISSUE TITLE
Syntax highlighting for Thymeleaf test (.thtest) files

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-extras-eclipse-plugin#24]
Create a new editor for the `.thtest` file extension, adding syntax highlighting, code completion, and all those goodies for Thymeleaf testing files.

This will probably be a massive task - I'll need to break it up into smaller pieces.

**Comment by danielfernandez** [comment]
Oh yes! yes yes yes yes! Do want! ;-);-)

**Comment by tduchateau** [comment]
:+1: :-)

**Comment by danielfernandez** [comment]
By the way, you might be able to use parts of the test file parsing logic in https://github.com/thymeleaf/thymeleaf-testing/blob/thymeleaf-testing-2.0.2/src/main/java/org/thymeleaf/testing/templateengine/standard/test/reader/StandardTestReader.java

**Comment by ultraq** [comment]
Doing some spring cleaning of issues, and I'm going to close this one - it's been open for over a decade so highly unlikely we'll get do this 😅
