### ISSUE TITLE
Move the bundled dialect XML files to their respective Thymeleaf projects

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-extras-eclipse-plugin#30]
Should we?  Discussion in the forums here: http://forum.thymeleaf.org/Dependencies-between-Thymeleaf-and-Thymeleaf-Eclipse-td4026812.html

**Comment by danielfernandez** [comment]
@ultraq remind me of this when 2.1.0-beta2 is out. If we finally decide doing it, 2.1.0 should be a good moment to start...

**Comment by opensource21** [comment]
2.1.0 is indeed a good starting point, but don't forget to put it in 2.0. Otherwise different eclispe-plugins are necessary.

**Comment by ultraq** [comment]
Done.  XML files have been copied to somewhere in the src/main/resources directory of their respective projects, currently in the 2.1-dev branches.
