### ISSUE TITLE
Content Assist doesn't work in Web Page Editor

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf-extras-eclipse-plugin#43]
I have the Thymeleaf plugin working happily in the HTML Editor, but Content Assist doesn't display any of the Thymeleaf attributes in the Web Page Editor (basically, a composite of the HTML Editor with a WebKit view). These appear to be essentially identical, so it looks like the Thymeleaf CA just isn't getting registered completely.

**Comment by ultraq** [comment]
Possibly fixed by #28 as the generic `IEditorPart` is also the parent interface for multi-part editors.  Should investigate that.

**Comment by ultraq** [comment]
Yup, it fixed it :)
