### ISSUE TITLE
Can't remove the Thymeleaf nature :-)

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf-extras-eclipse-plugin#45]
The remove action suffers from the same issue than in #42. :-(

If you wish, I can provide the same fix. Just tell me the branch for the PR!

**Comment by ultraq** [comment]
Hahahah!  The `2.1-dev` branch again please :)

**Comment by tduchateau** [comment]
OK!
But on this branch, I get lots of compile errors coming from the  package `org.thymeleaf.extras.eclipse.dialect` which is missing in the classpath.

Don't you have the same?

**Comment by ultraq** [comment]
Nope.  It might be related to the change in JARs from 2.0.x to 2.1.x.  There's a Gradle script on the root directory that, if you run `gradle downloadDependencies`, it should get all the JARs needed and put them into the libs folder for whatever plugins need whatever dependencies.  After that, you might need to then go into the core plugin manifest (double-click the plugin.xml file for the eclipse-plugin.core project) and on that first page there's a link, 'Update Classpath' that should update the project build path.

Problem is if you keep switching between the 2.0 and 2.1 branches, then 2.0 doesn't have this JAR and has all the JARs checked-in to git, whereas 2.1 doesn't and the JARs tend to linger.

**Comment by tduchateau** [comment]
Regarding the compile errors, actually it works like a charm when the project is imported using Gradle-related stuff, thanks :-)
