### ISSUE TITLE
Improve (even more) the restriction feature

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf-extras-eclipse-plugin#48]
As a continuation of the #17, it would be great to restrict the help depending not only on the presence of another attribute but also on its value.

Example1:

```
<table id="myTableId" dt:table="false" dt:url="..." ...>
```

In the example above, the suggestion for the `dt:url` processor should not appear if `dt:table="false"` whereas it should if `dt:table="true"`.

Example2:
Better example: my dialect contains an attribute processor that has different usages depending on the value of another attribute.

Here, the `dt:type` attribute waits for an export type (csv, pdf, ...)

```
<div dt:confType="export" dt:type="csv" ...></div>
```

Whereas here, the `dt:type` waits for a predefined value (init, createdrow, ...)

```
<div dt:confType="callback" dt:type="init" ...></div>
```

Of course, it would be great to display the right help depending on the value passed in the `dt:confType` attribute.

As a suggestion, some syntaxes like the following could help:

```
<restrictions tags="div" attributes="dt:confType=export" />
```

Or:

```
<restrictions tags="div" attributes="dt:confType#callback" />
```

**Comment by ultraq** [comment]
Modified the attribute restrictions to work like proposed in that first syntax, where supplying a value means that the attribute processor will only be proposed if both the attribute exists AND the attribute value matches.

Just like the existing behaviour, adding a -  (minus symbol) to the beginning of the restriction means that the attribute processor will only be proposed if the attribute doesn't exist, or if it does, that the attribute values don't match.

**Comment by tduchateau** [comment]
It works perfectly! :+1:
