### ISSUE TITLE
Start a test suite for the plugin

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-extras-eclipse-plugin#49]
The Eclipse plugin is already quite large and could benefit from some kind of test suite.  So: learn how Eclipse plugin tests are done so I can start creating one.  This task could probably be deferred until we need to do some refactoring.

**Comment by tduchateau** [comment]
:+1:

**Comment by ultraq** [comment]
Some unit tests are now included in 3.1.0 since Tycho has added support for co-located tests in recent years.  Closing.
