### ISSUE TITLE
i think it does not working with eclipse luna 4.4.0

### ISSUE THREAD

**Issue by happyprg** [thymeleaf/thymeleaf-extras-eclipse-plugin#55]
i think it does not working with eclipse luna 4.4.0

**Comment by ultraq** [comment]
You might be right - I've only just got a working Luna environment, and haven't had the chance to test it there yet.

**Comment by happyprg** [comment]
when we are possible to use thymeleaf-extras-eclipse-plugin with eclipse luna? :)

**Comment by ultraq** [comment]
Maybe this weekend?  I think I'll have some time to look into it then.  Hopefully it'll just need an updating of dependencies or something simple like that, instead of having to rework things because of a change in the API.

**Comment by ultraq** [comment]
Hmm, I just tried installing 2.1.3 of the plugin in my Luna setup, and it worked fine - I was able to get content assist working in an existing project without the Thymeleaf nature (Windows 7, Java 8 JDK on a Java 7 WTP project).  Are you having trouble getting content assist showing up in your Luna installation?

**Comment by happyprg** [comment]
![2014-07-15 8 17 00](https://cloud.githubusercontent.com/assets/779556/3583956/9c1be55a-0c11-11e4-880c-b0b8a4578127.png)
i installed 2.1.1 by install update sites.. http://www.thymeleaf.org/eclipse-plugin-update-site/
how can i use 2.1.3?

**Comment by happyprg** [comment]
and.. i think something wrong.
html viewer is not highlighting.. including thymeleaf tags..
![2014-07-15 8 18 42](https://cloud.githubusercontent.com/assets/779556/3583974/dff72780-0c11-11e4-9943-7512b937d949.png)

**Comment by happyprg** [comment]
sorry i use defaulteditor in eclipse,
i changed  html editor.
after that, it's working.
thanks. and sorry :)

**Comment by ghost** [comment]
I am using Eclipse 4.5 M7. and the plugin doesn't work for me.

**Comment by ultraq** [comment]
> I am using Eclipse 4.5 M7. and the plugin doesn't work for me.

I've just raised a new issue to investigate that here: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/62
