### ISSUE TITLE
Update site down

### ISSUE THREAD

**Issue by jimmyfm** [thymeleaf/thymeleaf-extras-eclipse-plugin#58]
I tried to install the plugin trough the update site url ( http://www.thymeleaf.org/eclipse-plugin-update-site/ ) but it gave me a 404 error

**Comment by ultraq** [comment]
Did you enter that URL into Eclipse as an update site URL (eg: when trying to install a plugin or search for plugins to install), or try to got to the URL in your browser?  Using it in Eclipse will work, but using it in your browser will give the 404.

**Comment by jimmyfm** [comment]
It worked perfectly, thanks @ultraq !
Shame on me for stopping at 404 and not trying fruther.
