### ISSUE TITLE
Content assist doesn't work with Eclipse  Neon.3 Release (4.6.3)

### ISSUE THREAD

**Issue by hellojavajs** [thymeleaf/thymeleaf-extras-eclipse-plugin#73]
I  installed 2.1.2  by update sites   http://www.thymeleaf.org/eclipse-plugin-update-site/

## Environment
      Mac OSX EI Captian 10.11.6
      Eclipse Neon.3 Release (4.6.3)
      java version "1.8.0_73"

**Comment by shuanshuan** [comment]
not a issue. Right click the project -->Thymeleaf--> Add thymeleaf Nature.

**Comment by qrqhuang** [comment]
after i added the nature, it still not working...

**Comment by shuanshuan** [comment]
@qrqhuang , try restart your eclipse.

1. add dependency to  pom.xml 
2. Right click the project -->Thymeleaf--> Add thymeleaf Nature.
3. restart your eclipse.

**Comment by qrqhuang** [comment]
@shuanshuan 
 I do nothing After that. But now it works .   
Thanks.

**Comment by shuanshuan** [comment]
I think it's step 3: restart your eclipse. 
When it's not working , you close it. You open eclipse today, it' working
