### ISSUE TITLE
Unable to add thymeleaf nature in eclipse oxygen

### ISSUE THREAD

**Issue by javautil** [thymeleaf/thymeleaf-extras-eclipse-plugin#74]
I select it and it does nothing.

Remove thymeleaf nature is not selectable after selecting.

I am using eclipse oxygen and

    Thymeleaf Content Assist source code	2.1.2.201603041014

**Comment by LOGANLEEE** [comment]
i do have same symptoms.. it's very stressful cuz can't use any content assist at all.
i'm considering back to neon..

**Comment by ultraq** [comment]
Grouping the "thymeleaf nature" issues, will track against #73.
