### ISSUE TITLE
Add to Eclipse Marketplace

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-extras-eclipse-plugin#78]
This one came through via Twitter: https://twitter.com/dr_pompeii/status/987002150571081729  This plugin isn't on the Eclipse Marketplace, so it might be good to add ourselves there.

Also, if they host plugins, then this might do away with us self-hosting the plugin using a combination of GitHub Pages and SourceForge, which has shown to have a lower-than-desired reliability rate as devs have been reporting random errors/problems when trying to install this plugin over the years!

**Comment by jiafuzhang** [comment]
强烈建议添加到Eclipse Marketplace！！！

**Comment by turionboy** [comment]
支持

**Comment by ultraq** [comment]
Solution submitted to Eclipse marketplace, pending review/approval now.  I'll try make sure it works (install the plugin via marketplace instead of the traditional means) before closing.  After that, the readme should also be updated to advertise this method of installation.

**Comment by manueljordan** [comment]
Let me know when be ready, just in these days I am going to install STS 3.9.5 and I must re install my set of plugins ...

**Comment by ultraq** [comment]
Woo!  Approved and it's now available on the Eclipse marketplace!

Marketplace website: http://marketplace.eclipse.org/content/thymeleaf-plugin-eclipse

Using the marketplace client within Eclipse:

<img width="550" alt="screen shot 2018-08-09 at 7 35 13 pm" src="https://user-images.githubusercontent.com/1686920/43887674-a563150c-9c13-11e8-9fd6-9bee4d88101d.png">

And it working (after I remembered the keys to press to bring up content assist!):

![content assist](https://user-images.githubusercontent.com/1686920/43887677-a894845e-9c13-11e8-9b12-3a1549934547.gif)

I'll update the readme to include this additional installation mechanism, but for anybody reading: search the marketplace for "thymeleaf" and it should be the only result 😄 

Noticed that installing it came with a signing warning though, so I might raise a separate issue to try sort that out.  Then again, installing STS did the same for its default install, so I guess it's a normal part of installing all these third-party plugins.

EDIT: This was tested using Eclipse Photon, the "for Java EE Developers" version so it had the Web Tools Platform already installed, which is a prerequisite for this plugin.
