### ISSUE TITLE
Add code-completion for SpringStandard dialect (th:field and th:errors)

### ISSUE THREAD

**Issue by rreimann** [thymeleaf/thymeleaf-extras-eclipse-plugin#8]
Currently there seems to be no code-completion support for the SpringStandard dialect, containing th:field and th:errors.

I would appreciate if code-completion for SpringStandard could be added.

**Comment by ultraq** [comment]
Of course - I can't believe I forgot about the Spring dialect!

**Comment by ultraq** [comment]
Checked-in code that adds support for the SpringStandard dialect.  Will be a part of the next release.
