### ISSUE TITLE
Plugin do thymeleaf na versão 2018-2019 do eclipse(4.9.0)

### ISSUE THREAD

**Issue by Renato28** [thymeleaf/thymeleaf-extras-eclipse-plugin#80]
instalei o plugin do thymeleaf no eclipse e percebi que algumas tags como th:field e th:errors não estão funcionando na versão 2018-09 (4.9.0) do eclipse, alguem tem a correção desse bug?
![bug](https://user-images.githubusercontent.com/23478461/49250095-c065b800-f3fc-11e8-93c4-b68e91729d48.png)

**Comment by ultraq** [comment]
I'm sorry, I don't speak Portuguese, but I've found that most of the autocomplete errors are a Java 9+ compatibility problem.  See: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/91#issuecomment-636403589  I am also tracking the fix against that issue.
