### ISSUE TITLE
Plug-in not working in Eclipse 4.10

### ISSUE THREAD

**Issue by jvs64893** [thymeleaf/thymeleaf-extras-eclipse-plugin#81]
Using Eclipse 4.10 I'm not able to activate the plug-in. When I try to click "Thymeleaf -> Add Thymeleaf Nature" nothing happens.

I then tried to activate it via "Project Natures", which shows this error:
>   Plug-in org.thymeleaf.extras.eclipse.core was unable to load class org.thymeleaf.extras.eclipse.nature.ThymeleafNature.
>   An error occurred while automatically activating bundle org.thymeleaf.extras.eclipse.core (973).

**Comment by rudolfschmidt** [comment]
Same Issue here

**Comment by delfuego** [comment]
Same same. Any thoughts on how to fix this?

**Comment by ultraq** [comment]
Likely a Java 9+ compatibility issue, see: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/91#issuecomment-636403589  Tracking the fix against that issue too.
