### ISSUE TITLE
is there any plugin for spring tool suite

### ISSUE THREAD

**Issue by naidukr** [thymeleaf/thymeleaf-extras-eclipse-plugin#83]

**Comment by ultraq** [comment]
Just going through some old issues to do a cleanup.  The latest version of this plugin (3.0.1) can work with Spring Tool Suite, but only versions older than 4.8.0.  From 4.8.0, STS started using a different HTML editor than what this plugin was built on, and so no longer works.  There's another issue, #92, for support in the newer versions of STS.
