### ISSUE TITLE
Thymeleaf Explorer

### ISSUE THREAD

**Issue by sparty02** [thymeleaf/thymeleaf-extras-eclipse-plugin#9]
![Thymeleaf Explorer](https://f.cloud.github.com/assets/1483538/120952/9367a49e-6d57-11e2-891b-4e642eeb2838.png)

It would be great to have some kind of "Thymeleaf Explorer" view in Eclipse.  This could be a separate view and/or node in the existing Eclipse project explorer.  See Spring's "Spring Elements" implementation as a reference.  This would make it nice to easily get to Thymeleaf templates, fragments, etc....

**Comment by ultraq** [comment]
An interesting idea, and I can definitely see the value in this - I often go back-and-forth between my own HTML pages looking for fragment points I've added so I can include them in other pages.

I've just started getting into using more of Spring (I currently only use it for Spring Security, but I'm now looking to it to handle code injection, data sources, MVC), so I'll take some time to get used to the Spring Explorer / Spring Elements node to get an idea of how I could do something similar for Thymeleaf.

**Comment by ultraq** [comment]
Doing some spring cleaning of issues, and I'm going to close this one - it's been open for over a decade so highly unlikely we'll get do this 😅
