### ISSUE TITLE
Eclipse with Spring Tool Suite 4.8.0+

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-extras-eclipse-plugin#92]
Much of the testing of this plugin has been with "vanilla" Eclipse (the "Java EE" version that's available for download), but a few reports recently have included Spring Tool Suite (STS) - no surprise given that Thymeleaf is often used with Spring projects.

So try install STS and verify if the plugin continues to work.  If it doesn't, then hopefully the fix is a simple oversight, otherwise I might have to see how to make it work with STS 😕 

See: #83, #91

**Comment by Fennzo** [comment]
@ultraq I'm using STS for a spring boot project, after installing the plugin and adding thymeleaf nature, the content assist doesn't seem to work. Is there something I'm doing wrong?

**Comment by Fennzo** [comment]
@ultraq Thanks, I will wait for the next update to work with jdk14

**Comment by ultraq** [comment]
Arg, STS from 4.8.0 uses a different editor for web-related files 🤦‍♂️ 😭  Copying what I wrote down elsewhere:

> Had a look at this, and I think STS won't work with this plugin any more. Even after looking into the bundled javax.activation JAR, I'm getting build errors everywhere using STS. It seems that, as of STS 4.8.0, they started moving to a different editor for web development to something called Wild Web Developer (spring-projects/sts4#354). This plugin was written atop the Eclipse's Web Tools Platform (WTP) project instead, which ships as part of the "Eclipse for Java and Web developers" edition from the Eclipse website.

**Comment by ultraq** [comment]
STS 4.7.1 and older should now work with 3.0.1 as it bundles all of the dependencies (this plugin was originally designed for the "Enterprise and Java Web Developers" bundle of Eclipse IDE which included them).

I'll rename this issue to reflect that it's for 4.8.0+, which is now using Wild Web Developer for editing HTML files.

**Comment by ultraq** [comment]
The HTML editor in STS has long since changed, whereas development on this plugin is just to keep in maintained/installable on newer Eclipse installations for those who still use the old editor.  I've added a note in the README about just keeping this plugin to maintenance mode, so it's unlikely we'll fix this for STS.  Closing.
